# Generated by Django 5.0.6 on 2024-07-15 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='coment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='start',
            new_name='stars',
        ),
    ]
